name: hug_ai_docs
description: Documentation for HugAI

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  jaspr: ^0.19.1
  jaspr_content: ^0.2.0
  jaspr_router: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.1.5+1
  jaspr_builder: ^0.19.1
  jaspr_lints: ^0.4.0
  lints: ^5.0.0

jaspr:
  mode: static
